# Generated by Django 4.0.4 on 2022-05-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='user',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
