# Generated by Django 4.0.4 on 2022-05-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='pswd2',
        ),
    ]
