# Generated by Django 4.0.4 on 2022-05-31 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='finalamount',
        ),
    ]
