# Generated by Django 4.0.4 on 2022-05-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_cart_finalamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amt',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
