# Generated by Django 4.0.4 on 2022-05-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='user',
            new_name='opt_user',
        ),
    ]
