# Generated by Django 4.0.4 on 2022-05-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_remove_customer_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='uname',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lname',
        ),
    ]
