# Generated by Django 4.0.4 on 2022-05-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_check_pdtl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_pdtl',
            name='finalamount',
        ),
        migrations.AddField(
            model_name='cart',
            name='finalamount',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
