# Generated by Django 4.0.4 on 2022-05-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_remove_check_pdtl_finalamount_cart_finalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='finalamount',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
